version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "krg"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-w60fyqb0q8zs"
s3_prefix = "krg"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "helloSignApiKey=\"\""
